# This is a basic workflow to help you get started with Actions

name: CI


on: push
jobs:
  first-job:
    runs-on: windows-latest
    container: node 17.6.0
    steps:
      - run: node --version
      - run: npm --version

