# This is a basic workflow to help you get started with Actions

name: CI


on: push
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - run: node --version
      - run: npm --version
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo "::endgroup::"

